### ISSUE TITLE
update_document_meta - Not using proper default index value

### ISSUE THREAD

**Issue by wrong1man** [qdrant/qdrant-haystack#14]
Hey, coming from:
https://github.com/deepset-ai/haystack/issues/4919

the fix suggested there under a comment is the proper one :)

The issue:
 _When using: update_document_meta(<doc_id>, <new_meta>), if we do not define index="Document" it will try to update the collection "None" instead of using the default "Document"._

the fix:
add to update_document_meta:
```
if not index: 
             index = self.index 
```

**Comment by kacperlukawski** [comment]
Hi @wrong1man, Thanks for spotting that! I'll provide a fix soon!

**Comment by kacperlukawski** [comment]
It should be fixed in the next release - @wrong1man, please update to 1.0.1 ;)
