### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by adityaguru149** [qdrant/qdrant-haystack#18]
I see python 3.11+ is not supported at present `python = ">=3.8.1,<=3.11`.
Is there some know issue or it is just not tested?

How to enable support for python 3.11+?

**Comment by kacperlukawski** [comment]
@adityaguru149 Python 3.12 is still in a beta preview

**Comment by TuanaCelik** [comment]
@kacperlukawski I think with the current setup of the poetry config file you also won't get the patch releases of 3.11 though. So you'll get a conflict if you have say 3.11.1 installed. Changing it to <3.12 should do it?

**Comment by kacperlukawski** [comment]
@TuanaCelik You're absolutely right. Thanks for noticing that! I'll be changed soon.
