### ISSUE TITLE
Cannot import QdrantDocumentStore due to import error

### ISSUE THREAD

**Issue by burtonrj** [qdrant/qdrant-haystack#23]
Hi, I'm using qdrant-haystack version 1.0.4 with haystack version 1.18.1. When I try to import `QdrantDocumentStore` I get the following import error:

ImportError: cannot import name 'get_batches_from_generator' from 'haystack.document_stores.base' 

Checking the haystack main branch, `get_batches_from_generator` appears to be missing from `haystack.document_stores.base`. It looks like it has been moved to `haystack.utils.batching` but you might need to double-check this is the same function.

**Comment by kacperlukawski** [comment]
@burtonrj Thanks for letting me know, the fix it's almost ready.

**Comment by kacperlukawski** [comment]
@burtonrj Fixed in 1.0.5

**Comment by burtonrj** [comment]
Just back to say this worked perfectly, thanks for the quick fix.
