### ISSUE TITLE
How to pass metadata to QdrantClient

### ISSUE THREAD

**Issue by MathiasSpanhove** [qdrant/qdrant-haystack#26]
I see that due to #19 and #20 that **kwargs has been removed from the QdrantDocumentStore `__init__`.
Is there a workaround to pass metadata to the QdrantClient?

Currently the following code doesn't work:
```python
document_store = (
    QdrantDocumentStore(
        url=f"{QDRANT_APP_URL}",
        port=443,
        index=f"{QDRANT_INDEX}",
        embedding_dim=768,
        recreate_index=True,
        timeout=120,
        similarity="cosine",
        metadata={"Authorization": f"Bearer {get_user_token()}"}
    )
)
```

**Comment by kacperlukawski** [comment]
@MathiasSpanhove It might not be the most elegant solution to that, but could you please verify if that works?

```python
document_store._client._rest_headers = {"Authorization": f"Bearer {get_user_token()}"}
```

It seems to be an ugly workaround, but I can't see a different way.

**Comment by MathiasSpanhove** [comment]
I could also create a PR with something like the following:

```python
@classmethod
def from_qdrant_client(cls, client: qdrant_client.QdrantClient, **kwargs):
    cls.client = client
    return cls(**kwargs)
```

And add a check in the `__init__` to make sure that the client hasn't already been provided?
This way all current implementations would keep working.

Let me know what you think and if you would like a PR!

**Comment by MathiasSpanhove** [comment]
> I think we can expose the `metadata` parameter, as long as it doesn't break the YAML pipelines. Would you like to contribute?

I've made a PR that exposes the metadata parameter and doesn't break the YAML pipeline.
