### ISSUE TITLE
dependency conflict tiktoken

### ISSUE THREAD

**Issue by hollandmdwx** [qdrant/qdrant-haystack#34]
Hello, 
I ran into a dependency conflict with haytsack and qdrant-haystack. 
According to the dependecies list in pyproject.toml  "tiktoken<=0.4.0" is required while haystack requires "tiktoken>=0.5.1". 

Is the version mandatory or is it possible to customize it?

**Comment by kacperlukawski** [comment]
Hi @hollandmdwx , thanks for bringing this up! Haystack had an issue with `tiktoken` `0.4.1`, so we also restricted it. Btw, the new version `qdrant-haystack==1.0.11` has been just released and it sets the allowed version to `0.5.1`
