### ISSUE TITLE
Specify HNSW Parameters

### ISSUE THREAD

**Issue by danielfleischer** [qdrant/qdrant-haystack#7]
Hi, are you planning to allow passing HNSW parameters when creating a new collection? if not, would you accept a PR? thanks!

**Comment by kacperlukawski** [comment]
Hi @danielfleischer, We'll gladly accept a PR on that topic. Please let me know if you need any help!

**Comment by danielfleischer** [comment]
Hi, I submitted #8; please have a look.

**Comment by kacperlukawski** [comment]
@danielfleischer Done. Thanks for the contribution! I had just a single minor comment.
